/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PmiAmbulanceWlList {
    }
}
declare global {
    interface HTMLPmiAmbulanceWlListElement extends Components.PmiAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLPmiAmbulanceWlListElement: {
        prototype: HTMLPmiAmbulanceWlListElement;
        new (): HTMLPmiAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "pmi-ambulance-wl-list": HTMLPmiAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface PmiAmbulanceWlList {
    }
    interface IntrinsicElements {
        "pmi-ambulance-wl-list": PmiAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pmi-ambulance-wl-list": LocalJSX.IntrinsicElements["pmi-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLPmiAmbulanceWlListElement>;
        }
    }
}
